site_name: YMM4 API Documentation
site_url: https://ymm-api.pages.dev/
repo_url: https://github.com/p-rer/YMM4-API-Document
repo_name: p-rer/YMM4-API-Document
edit_uri: edit/master/docs/
site_description: YMM4のプラグインの作成に必要なアセンブリのドキュメント及び作成の手順を解説するサイトです。
theme:
  name: material
  language: ja
  icon:
    repo: fontawesome/brands/git-alt
    logo: material/file-document-multiple
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - search.suggest
    - toc.follow
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.footer
    - navigation.path
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - content.action.edit
extra:
  consent:
    title: Cookie consent
    description:
      このサイトはユーザーエクスペリエンスの向上のため、Cookieを使用しています。
            あなたがこのサイト内での自分の行動が追跡されることを嫌う場合、Cookieを使用しないことを選択することも可能です。
            Cookieを使用することに同意しますか？
    actions:
      - accept
      - reject
plugins:
  - privacy
  - open-in-new-tab
  - search
  - git-revision-date-localized:      
      timezone: Asia/Tokyo
      locale: ja
      enable_creation_date: true
  - offline
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      use_pygments: true
      noclasses: false
      pygments_style: monokai
      linenums: false
  - pymdownx.superfences
  - toc:
      toc_depth: 2-3
      permalink: true
